variables:
  HEROKU_APP_NAME: "drawgo-test"
  
stages:
  - deploy

heroku-deploy:
  stage: deploy
  image: ruby:latest
  only:
    - main
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
